import { db } from '@/db';
import { expenses } from '@/db/schema';

async function main() {
    const sampleExpenses = [
        {
            userId: 1,
            title: 'Business lunch with client',
            amount: 85.00,
            currency: 'USD',
            category: 'Meals',
            description: 'Lunch meeting with potential client to discuss new project requirements',
            receiptUrl: 'https://example.com/receipts/lunch-client-001.pdf',
            status: 'approved',
            submittedAt: new Date('2024-01-15T14:30:00Z').toISOString(),
            createdAt: new Date('2024-01-15T10:00:00Z').toISOString(),
            updatedAt: new Date('2024-01-16T09:00:00Z').toISOString(),
        },
        {
            userId: 2,
            title: 'Software license renewal',
            amount: 299.00,
            currency: 'USD',
            category: 'Software',
            description: 'Annual renewal for Adobe Creative Suite license',
            receiptUrl: 'https://example.com/receipts/adobe-renewal-2024.pdf',
            status: 'pending',
            submittedAt: new Date('2024-01-20T16:45:00Z').toISOString(),
            createdAt: new Date('2024-01-20T16:30:00Z').toISOString(),
            updatedAt: new Date('2024-01-20T16:45:00Z').toISOString(),
        },
        {
            userId: 3,
            title: 'Conference travel expenses',
            amount: 1200.00,
            currency: 'USD',
            category: 'Travel',
            description: 'Flight and hotel for Tech Conference 2024 in San Francisco',
            receiptUrl: 'https://example.com/receipts/conference-travel-2024.pdf',
            status: 'approved',
            submittedAt: new Date('2024-01-25T11:20:00Z').toISOString(),
            createdAt: new Date('2024-01-25T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-01-26T14:30:00Z').toISOString(),
        },
        {
            userId: 1,
            title: 'Ergonomic office chair',
            amount: 450.00,
            currency: 'USD',
            category: 'Office Supplies',
            description: 'Herman Miller ergonomic chair for workstation setup',
            status: 'pending',
            submittedAt: new Date('2024-02-01T13:15:00Z').toISOString(),
            createdAt: new Date('2024-02-01T12:45:00Z').toISOString(),
            updatedAt: new Date('2024-02-01T13:15:00Z').toISOString(),
        },
        {
            userId: 2,
            title: 'Team dinner celebration',
            amount: 180.00,
            currency: 'USD',
            category: 'Meals',
            description: 'Dinner celebration for successful project completion',
            receiptUrl: 'https://example.com/receipts/team-dinner-feb.pdf',
            status: 'approved',
            submittedAt: new Date('2024-02-05T19:30:00Z').toISOString(),
            createdAt: new Date('2024-02-05T18:00:00Z').toISOString(),
            updatedAt: new Date('2024-02-06T10:00:00Z').toISOString(),
        },
        {
            userId: 3,
            title: 'Taxi to airport',
            amount: 45.50,
            currency: 'EUR',
            category: 'Travel',
            description: 'Taxi fare from hotel to airport in Amsterdam',
            receiptUrl: 'https://example.com/receipts/taxi-amsterdam.pdf',
            status: 'approved',
            submittedAt: new Date('2024-02-08T08:30:00Z').toISOString(),
            createdAt: new Date('2024-02-08T08:15:00Z').toISOString(),
            updatedAt: new Date('2024-02-09T12:00:00Z').toISOString(),
        },
        {
            userId: 1,
            title: 'Office supplies restock',
            amount: 125.75,
            currency: 'USD',
            category: 'Office Supplies',
            description: 'Printer paper, pens, notebooks, and other office materials',
            status: 'draft',
            submittedAt: null,
            createdAt: new Date('2024-02-10T14:20:00Z').toISOString(),
            updatedAt: new Date('2024-02-10T14:20:00Z').toISOString(),
        },
        {
            userId: 2,
            title: 'Cloud storage upgrade',
            amount: 2500.00,
            currency: 'USD',
            category: 'Software',
            description: 'Upgrade to enterprise cloud storage plan for team collaboration',
            status: 'rejected',
            submittedAt: new Date('2024-02-12T10:00:00Z').toISOString(),
            createdAt: new Date('2024-02-12T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-14T16:45:00Z').toISOString(),
        },
        {
            userId: 3,
            title: 'Coffee with vendor',
            amount: 15.25,
            currency: 'GBP',
            category: 'Meals',
            description: 'Coffee meeting with potential vendor in London',
            receiptUrl: 'https://example.com/receipts/coffee-vendor-london.pdf',
            status: 'approved',
            submittedAt: new Date('2024-02-15T11:45:00Z').toISOString(),
            createdAt: new Date('2024-02-15T11:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-16T09:15:00Z').toISOString(),
        },
        {
            userId: 1,
            title: 'Training course materials',
            amount: 89.99,
            currency: 'USD',
            category: 'Other',
            description: 'Books and materials for professional development course',
            status: 'pending',
            submittedAt: new Date('2024-02-18T15:30:00Z').toISOString(),
            createdAt: new Date('2024-02-18T14:45:00Z').toISOString(),
            updatedAt: new Date('2024-02-18T15:30:00Z').toISOString(),
        },
        {
            userId: 2,
            title: 'Client presentation materials',
            amount: 67.80,
            currency: 'USD',
            category: 'Office Supplies',
            description: 'Presentation folders, business cards, and printed materials',
            receiptUrl: 'https://example.com/receipts/presentation-materials.pdf',
            status: 'approved',
            submittedAt: new Date('2024-02-20T12:15:00Z').toISOString(),
            createdAt: new Date('2024-02-20T11:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-21T08:45:00Z').toISOString(),
        },
        {
            userId: 3,
            title: 'Parking fees downtown',
            amount: 25.00,
            currency: 'USD',
            category: 'Travel',
            description: 'Daily parking for client meetings downtown',
            status: 'draft',
            submittedAt: null,
            createdAt: new Date('2024-02-22T17:00:00Z').toISOString(),
            updatedAt: new Date('2024-02-22T17:00:00Z').toISOString(),
        },
        {
            userId: 1,
            title: 'Design software subscription',
            amount: 199.00,
            currency: 'EUR',
            category: 'Software',
            description: 'Monthly subscription for Figma professional plan',
            receiptUrl: 'https://example.com/receipts/figma-subscription.pdf',
            status: 'approved',
            submittedAt: new Date('2024-02-25T09:00:00Z').toISOString(),
            createdAt: new Date('2024-02-25T08:45:00Z').toISOString(),
            updatedAt: new Date('2024-02-26T10:30:00Z').toISOString(),
        },
        {
            userId: 2,
            title: 'Internet upgrade for home office',
            amount: 75.00,
            currency: 'USD',
            category: 'Other',
            description: 'Upgrade to high-speed internet for remote work productivity',
            status: 'pending',
            submittedAt: new Date('2024-02-28T14:20:00Z').toISOString(),
            createdAt: new Date('2024-02-28T13:45:00Z').toISOString(),
            updatedAt: new Date('2024-02-28T14:20:00Z').toISOString(),
        },
        {
            userId: 3,
            title: 'Working lunch with team',
            amount: 95.40,
            currency: 'GBP',
            category: 'Meals',
            description: 'Working lunch to discuss quarterly planning with team members',
            receiptUrl: 'https://example.com/receipts/team-lunch-march.pdf',
            status: 'approved',
            submittedAt: new Date('2024-03-02T13:45:00Z').toISOString(),
            createdAt: new Date('2024-03-02T12:30:00Z').toISOString(),
            updatedAt: new Date('2024-03-03T11:15:00Z').toISOString(),
        },
        {
            userId: 1,
            title: 'Hotel accommodation',
            amount: 185.75,
            currency: 'USD',
            category: 'Travel',
            description: 'One night hotel stay for client meeting in Chicago',
            status: 'rejected',
            submittedAt: new Date('2024-03-05T16:30:00Z').toISOString(),
            createdAt: new Date('2024-03-05T15:45:00Z').toISOString(),
            updatedAt: new Date('2024-03-07T09:20:00Z').toISOString(),
        },
        {
            userId: 2,
            title: 'External hard drive',
            amount: 129.99,
            currency: 'USD',
            category: 'Office Supplies',
            description: '2TB external hard drive for project backups and file storage',
            status: 'draft',
            submittedAt: null,
            createdAt: new Date('2024-03-08T10:15:00Z').toISOString(),
            updatedAt: new Date('2024-03-08T10:15:00Z').toISOString(),
        },
        {
            userId: 3,
            title: 'Professional development webinar',
            amount: 149.00,
            currency: 'USD',
            category: 'Other',
            description: 'Registration fee for advanced project management webinar series',
            receiptUrl: 'https://example.com/receipts/webinar-registration.pdf',
            status: 'pending',
            submittedAt: new Date('2024-03-10T11:30:00Z').toISOString(),
            createdAt: new Date('2024-03-10T10:45:00Z').toISOString(),
            updatedAt: new Date('2024-03-10T11:30:00Z').toISOString(),
        }
    ];

    await db.insert(expenses).values(sampleExpenses);
    
    console.log('✅ Expenses seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});